Fix UnicodeEncodeError in `generate_registry_tables.py`
 - Fixed an issue in generate_registry_tables.py script where a UnicodeEncodeError occurred due to non-ASCII characters in the XML content. The fix ensures correct handling of Unicode characters by decoding the XML content with UTF-8 encoding before parsing.

 - Error Message:

  Traceback (most recent call last):
    File "./tools/src/external/angle/third_party/vulkan-deps/spirv-tools/src/utils/generate_registry_tables.py", line 92, in <module>
      main()
    File "./tools/src/external/angle/third_party/vulkan-deps/spirv-tools/src/utils/generate_registry_tables.py", line 84, in main
      registry = XML(xml_in.read(), parser=parser)
    File "internal/stdlib/xml/etree/ElementTree.py", line 1311, in XML
    File "internal/stdlib/xml/etree/ElementTree.py", line 1657, in feed
  UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 7365: ordinal not in range(128)
  exit status 1

Signed-off-by: Christopher <mizdrake7@gmail.com>